// weekly_prep.ts — O83: the weekly agent prep digest.
//
// The ideas doc's spec: "archive integrity sweep → drive scan deltas →
// redundancy check → new-music-not-yet-exported report → markdown digest.
// The agent writes nothing — the weekly digest implemented by an operator
// that never gets bored."
//
// Everything it consumes is ALREADY collected by the server: preflight (B12),
// fleet redundancy (B7), archive ingest status + lowq queue (O82b). This
// module is the pure renderer: data in → markdown out. `deckctl prep` runs
// it (fetch + render + write); a cron/agent loop just calls that command.

import type { RedundancyVerdict } from "../shared/types";
import type { PreflightReport } from "./preflight";

/** The weekly digest consumes the server's full PreflightReport directly —
 *  one type from producer to renderer, no structural-minimum drift. */
export type PreflightDigest = PreflightReport;

export interface RedundancyDigest {
  playlists: {
    name: string;
    /** Narrowed from RedundancyVerdict: "unknown" playlists are filtered
     *  out by the caller before rendering. */
    verdict: Exclude<RedundancyVerdict, "unknown">;
    missing_count: number;
  }[];
}

export interface IngestDigest {
  available: boolean;
  counts: Record<string, number>;
  total: number;
  recent_tracks: {
    title: string | null;
    artist: string | null;
    updated_at: string;
  }[];
}

export interface LowqDigest {
  available: boolean;
  tracks: { title: string | null; artist: string | null; reason: string }[];
}

/** D30 archive-integrity sweep results (bitrot/truncation early warning). */
export interface SweepDigest {
  available: boolean;
  checked: number;
  findings: {
    path: string;
    title: string | null;
    artist: string | null;
    verdict: string;
    detail: string;
  }[];
}

export interface WeeklyPrepInput {
  preflight: PreflightDigest;
  redundancy: RedundancyDigest;
  ingest: IngestDigest;
  lowq: LowqDigest;
  /** D30 sweep — optional: pre-migration digests render without it. */
  sweep?: SweepDigest;
}

const VERDICT_ICON: Record<string, string> = {
  ready: "🟢",
  attention: "🟡",
  "not-ready": "🔴",
  unknown: "⚪",
  pass: "✓",
  warn: "▲",
  fail: "✕",
};

function dateLine(now: number): string {
  return new Date(now).toISOString().slice(0, 10);
}

/** Fetch-and-render seam shared by `deckctl prep` and the `deck_prep` MCP
 *  tool (surface-parity: one implementation, two spokes). Data comes from
 *  the server's own reads — preflight, fleet redundancy, archive status,
 *  LOWQ queue, and the D30 archive-integrity sweep. */
export async function fetchWeeklyPrepInput(
  getJson: <T>(path: string, timeoutMs?: number) => Promise<T>,
): Promise<WeeklyPrepInput> {
  const [pf, redundancy, ingest, lowq, sweep] = await Promise.all([
    getJson<PreflightReport>("/api/preflight"),
    getJson<{
      playlists: {
        playlist: string;
        verdict: RedundancyVerdict;
        tracks: { at_risk: boolean }[];
      }[];
    }>("/api/fleet/redundancy"),
    getJson<IngestDigest>("/api/archive/ingest-status"),
    getJson<LowqDigest>("/api/archive/lowq"),
    // D30 sweep (~15s on the real archive): the default apiGet deadline is
    // 10s, so the sweep leg would time out and silently vanish from the
    // digest. Give it a deadline sized to the documented sweep duration.
    getJson<SweepDigest>("/api/archive/sweep", 60_000).catch(
      (): SweepDigest => ({ available: false, checked: 0, findings: [] }),
    ),
  ]);
  return {
    preflight: pf,
    redundancy: {
      playlists: redundancy.playlists
        .filter((p) => p.verdict !== "unknown")
        .map((p) => ({
          name: p.playlist,
          verdict: (p.verdict === "unknown" ? "warn" : p.verdict) as Exclude<
            RedundancyVerdict,
            "unknown"
          >,
          missing_count: p.tracks.filter((t) => t.at_risk).length,
        })),
    },
    ingest,
    lowq,
    sweep,
  };
}

/** The digest. Deterministic, markdown, one screen — built to be pasted into
 *  a chat or opened before a gig. Sections degrade gracefully: a missing
 *  archive DB renders "not available" instead of failing the whole digest. */
/** The digest. Deterministic, markdown, one screen — built to be pasted into
 *  a chat or opened before a gig. Sections degrade gracefully: a missing
 *  archive DB renders "not available" instead of failing the whole digest. */
export function renderWeeklyPrep(input: WeeklyPrepInput): string {
  const { preflight: pf } = input;
  const lines: string[] = [];

  lines.push(`# Weekly prep — ${dateLine(pf.generated_at)}`);
  lines.push("");
  lines.push(`**Fleet:** ${icon(pf.overall)} ${pf.overall} — ${pf.summary}`);
  lines.push("");
  lines.push(...preflightSection(input));
  lines.push(...redundancySection(input));
  lines.push(...archiveSection(input));
  lines.push(...lowqSection(input));
  lines.push(...sweepSection(input));
  lines.push(
    "_Generated by `deckctl prep` — reads only; run `deckctl preflight` for the live gate._",
  );
  return lines.join("\n");
}

function icon(v: string): string {
  return VERDICT_ICON[v] ?? "·";
}

/** Per-drive checks only where something needs eyes (ready drives with all
 *  passes stay collapsed — the point of prep is the exception list). */
function preflightSection(input: WeeklyPrepInput): string[] {
  const { preflight: pf } = input;
  const lines: string[] = [];
  for (const d of pf.drives) {
    if (!d.drive.mounted || d.overall === "ready") continue;
    lines.push(
      `## ${d.drive.nickname ?? d.drive.name} — ${icon(d.overall)} ${d.overall}`,
    );
    for (const c of d.checks) {
      if (c.status === "pass") continue;
      lines.push(`- ${icon(c.status)} **${c.label}** — ${c.detail}`);
      if (c.fix) lines.push(`  - fix: ${c.fix}`);
    }
    lines.push("");
  }
  return lines;
}

/** Redundancy: playlists that are not fully protected. */
function redundancySection(input: WeeklyPrepInput): string[] {
  const { redundancy } = input;
  const lines: string[] = [];
  const risky = redundancy.playlists.filter((p) => p.verdict !== "pass");
  lines.push("## Playlist redundancy");
  if (!risky.length) {
    lines.push("All playlists fully protected. ✓");
  } else {
    for (const p of risky)
      lines.push(
        `- ${icon(p.verdict)} **${p.name}** — ${p.missing_count} track(s) below floor`,
      );
  }
  lines.push("");
  return lines;
}

/** Archive half: downloads + newest imports. */
function archiveSection(input: WeeklyPrepInput): string[] {
  const { ingest } = input;
  const lines: string[] = [];
  lines.push("## Archive");
  if (!ingest.available) {
    lines.push("Archive DB not available (no downloads yet?).");
  } else {
    const downloaded = ingest.counts["downloaded"] ?? 0;
    const failed = ingest.counts["failed"] ?? 0;
    lines.push(
      `- ${downloaded} tracks downloaded of ${ingest.total} seen${
        failed ? ` · **${failed} failed** (retry pending)` : ""
      }`,
    );
    const recent = ingest.recent_tracks.slice(0, 5);
    if (recent.length) {
      lines.push("- newest:");
      for (const t of recent)
        lines.push(
          `  - ${t.artist ?? "?"} — ${t.title ?? "?"} (${(t.updated_at ?? "").slice(0, 10)})`,
        );
    }
  }
  lines.push("");
  return lines;
}

/** Low-quality upgrade queue: the actionable tail. */
function lowqSection(input: WeeklyPrepInput): string[] {
  const { lowq } = input;
  const lines: string[] = [];
  lines.push("## Low-quality queue");
  if (!lowq.available || !lowq.tracks.length) {
    lines.push("Nothing below the bitrate floor. ✓");
  } else {
    for (const t of lowq.tracks.slice(0, 10))
      lines.push(`- ${t.artist ?? "?"} — ${t.title ?? "?"}: ${t.reason}`);
    if (lowq.tracks.length > 10)
      lines.push(`- …and ${lowq.tracks.length - 10} more`);
  }
  lines.push("");
  return lines;
}

/** D30: archive integrity — bitrot/truncation BEFORE it reaches a drive. */
function sweepSection(input: WeeklyPrepInput): string[] {
  const { sweep } = input;
  const lines: string[] = [];
  if (sweep && sweep.available) {
    lines.push("## Archive integrity (D30 sweep)");
    if (!sweep.findings.length) {
      lines.push(`All ${sweep.checked} files match known-good hashes. ✓`);
    } else {
      for (const f of sweep.findings.slice(0, 10))
        lines.push(
          `- ${f.verdict}: ${f.artist ?? "?"} — ${f.title ?? "?"} (${f.detail})`,
        );
      if (sweep.findings.length > 10)
        lines.push(`- …and ${sweep.findings.length - 10} more`);
    }
    lines.push("");
  }
  return lines;
}
