// weekly_prep.ts — O83: the weekly agent prep digest.
//
// The ideas doc's spec: "archive integrity sweep → drive scan deltas →
// redundancy check → new-music-not-yet-exported report → markdown digest.
// The agent writes nothing — the weekly digest implemented by an operator
// that never gets bored."
//
// Everything it consumes is ALREADY collected by the server: preflight (B12),
// fleet redundancy (B7), archive ingest status + lowq queue (O82b). This
// module is the pure renderer: data in → markdown out. `deckctl prep` runs
// it (fetch + render + write); a cron/agent loop just calls that command.

/** Structural minimum of the preflight report (deckctl's wire payload is
 *  narrower than the server type — this accepts both). */
export interface PreflightDigest {
  generated_at: number;
  overall: string;
  summary: string;
  drives: {
    drive: { name: string; nickname: string | null; mounted: boolean };
    overall: string;
    checks: {
      label: string;
      status: string;
      detail?: string;
      fix?: string;
    }[];
  }[];
}

export interface RedundancyDigest {
  playlists: {
    name: string;
    verdict: "pass" | "warn" | "fail";
    missing_count: number;
  }[];
}

export interface IngestDigest {
  available: boolean;
  counts: Record<string, number>;
  total: number;
  recent_tracks: {
    title: string | null;
    artist: string | null;
    updated_at: string;
  }[];
}

export interface LowqDigest {
  available: boolean;
  tracks: { title: string | null; artist: string | null; reason: string }[];
}

export interface WeeklyPrepInput {
  preflight: PreflightDigest;
  redundancy: RedundancyDigest;
  ingest: IngestDigest;
  lowq: LowqDigest;
}

const VERDICT_ICON: Record<string, string> = {
  ready: "🟢",
  attention: "🟡",
  "not-ready": "🔴",
  unknown: "⚪",
  pass: "✓",
  warn: "▲",
  fail: "✕",
};

function dateLine(now: number): string {
  return new Date(now).toISOString().slice(0, 10);
}

/** The digest. Deterministic, markdown, one screen — built to be pasted into
 *  a chat or opened before a gig. Sections degrade gracefully: a missing
 *  archive DB renders "not available" instead of failing the whole digest. */
export function renderWeeklyPrep(input: WeeklyPrepInput): string {
  const { preflight: pf, redundancy, ingest, lowq } = input;
  const lines: string[] = [];
  const icon = (v: string) => VERDICT_ICON[v] ?? "·";

  lines.push(`# Weekly prep — ${dateLine(pf.generated_at)}`);
  lines.push("");
  lines.push(`**Fleet:** ${icon(pf.overall)} ${pf.overall} — ${pf.summary}`);
  lines.push("");

  // per-drive checks only where something needs eyes (ready drives with all
  // passes stay collapsed — the point of prep is the exception list)
  for (const d of pf.drives) {
    if (!d.drive.mounted || d.overall === "ready") continue;
    lines.push(
      `## ${d.drive.nickname ?? d.drive.name} — ${icon(d.overall)} ${d.overall}`,
    );
    for (const c of d.checks) {
      if (c.status === "pass") continue;
      lines.push(`- ${icon(c.status)} **${c.label}** — ${c.detail}`);
      if (c.fix) lines.push(`  - fix: ${c.fix}`);
    }
    lines.push("");
  }

  // redundancy: playlists that are not fully protected
  const risky = redundancy.playlists.filter((p) => p.verdict !== "pass");
  lines.push("## Playlist redundancy");
  if (!risky.length) {
    lines.push("All playlists fully protected. ✓");
  } else {
    for (const p of risky)
      lines.push(
        `- ${icon(p.verdict)} **${p.name}** — ${p.missing_count} track(s) below floor`,
      );
  }
  lines.push("");

  // archive half
  lines.push("## Archive");
  if (!ingest.available) {
    lines.push("Archive DB not available (no downloads yet?).");
  } else {
    const downloaded = ingest.counts["downloaded"] ?? 0;
    const failed = ingest.counts["failed"] ?? 0;
    lines.push(
      `- ${downloaded} tracks downloaded of ${ingest.total} seen` +
        (failed ? ` · **${failed} failed** (retry pending)` : ""),
    );
    const recent = ingest.recent_tracks.slice(0, 5);
    if (recent.length) {
      lines.push("- newest:");
      for (const t of recent)
        lines.push(
          `  - ${t.artist ?? "?"} — ${t.title ?? "?"} (${(t.updated_at ?? "").slice(0, 10)})`,
        );
    }
  }
  lines.push("");

  // low-quality upgrade queue: the actionable tail
  lines.push("## Low-quality queue");
  if (!lowq.available || !lowq.tracks.length) {
    lines.push("Nothing below the bitrate floor. ✓");
  } else {
    for (const t of lowq.tracks.slice(0, 10))
      lines.push(`- ${t.artist ?? "?"} — ${t.title ?? "?"}: ${t.reason}`);
    if (lowq.tracks.length > 10)
      lines.push(`- …and ${lowq.tracks.length - 10} more`);
  }
  lines.push("");

  lines.push(
    "_Generated by `deckctl prep` — reads only; run `deckctl preflight` for the live gate._",
  );
  return lines.join("\n");
}
