import type { CommandDocEntry } from "./command-doc-types";

export const REKORDBOX_COMMAND_DOCS: readonly CommandDocEntry[] = [
  {
    name: "rb-fix-paths",
    group: "fulltags",
    block: [
      "  megadj rb-fix-paths [drive] [--apply --yes] [--json]",
      "                                               repair stale rekordbox paths after folder",
      "                                               moves/merges: dry-run reports broken rows",
      "                                               and fixes (dry first, ALWAYS); --apply",
      "                                               backs the DB up, refuses while rekordbox",
      "                                               runs, rewrites, then re-checks EVERY row",
    ],
  },
  {
    name: "rb-unmatched",
    group: "fulltags",
    block: [
      "  megadj rb-unmatched [drive] [--ext E] [--json]",
      "                                               the disk→DB reconcile half: audio files NO",
      "                                               rekordbox row points at (import backlog).",
      "                                               Census classifies matched / twin-named",
      "                                               (dupescan's queue) / unknown; exit 1 while",
      "                                               unknown > 0 (dry first, ALWAYS);",
      "                                                [--quarantine --yes] moves ONLY unknown",
      "                                               files to the shelf quarantine (never",
      "                                               deletes; dated manifest beside them)",
    ],
  },
  {
    name: "rb-adopt",
    group: "fulltags",
    block: [
      "  megadj rb-adopt [drive] [--apply --yes] [--json]",
      "                                               mirror EVERY Rekordbox Content row into",
      "                                               archive.db with an exact Content-ID",
      "                                               cross-reference and full metadata JSON;",
      "                                               preserves YouTube/source IDs, dedupes one",
      "                                               physical file, backs archive.db up, and",
      "                                               verifies the complete census (dry first)",
    ],
  },
  {
    name: "rb-import",
    group: "fulltags",
    block: [
      "  megadj rb-import [drive] <folder> [--playlist NAME] [--group NAME]",
      "                                               [--allow-dupe] [--apply --yes]",
      "                                               [--json]",
      "                                               the sanctioned headless master-DB",
      "                                               import: one playlist per intake",
      "                                               folder (nested under --group),",
      "                                               DjmdContent rows for every audio",
      "                                               file, fingerprint dupe gate (F11;",
      "                                               --allow-dupe escapes), dated DB",
      "                                               backup, refuses while rekordbox",
      "                                               runs, whole-table verify after",
      "                                               write (dry first, ALWAYS)",
    ],
  },
  {
    name: "rb-cues",
    group: "fulltags",
    block: [
      "  megadj rb-cues [drive] [--restamp] [--ledger F] [--force] [--apply --yes] [--json]",
      "                                               THE djmdCue write seam (postmortem",
      "                                               F1/F3): dry-run counts only Sep 12",
      "                                               incident rows matching the proven",
      "                                               broken-hot-cue signature; --apply --yes",
      "                                               re-stamps those rows Kind=1 (hot),",
      "                                               preserving legitimate Kind=0 memory cues;",
      "                                               dated backup + re-read verify,",
      "                                               refuses while rekordbox runs",
    ],
  },
  {
    name: "rb-dedup",
    group: "fulltags",
    block: [
      "  megadj rb-dedup [drive] [--report] [--apply --yes] [--json]",
      "                                               fingerprint-ish duplicate sweep over",
      "                                               the master DB (postmortem F2/BUG-2):",
      "                                               finds same-title ±2s / same-path twin",
      "                                               rows, keeps the Contents/ canonical,",
      "                                               deletes loser rows + quarantines loser",
      "                                               files with a receipt (never deletes);",
      "                                               report default, dry first",
    ],
  },
  {
    name: "rb-comment-sync",
    group: "fulltags",
    block: [
      "  megadj rb-comment-sync [drive] [--batch TOKEN] [--apply --yes] [--json]",
      "                                               backfill rekordbox Comment from",
      "                                               the tags already on the files",
      "                                               (TXXX CAMELOT/ENERGY/MOOD) +",
      "                                               archive.db mood ledger, in the",
      "                                               FullTags Key-E-Moods format;",
      "                                               never clobbers non-empty comments",
      "                                               (dry first)",
    ],
  },
  {
    name: "rb-playlist",
    group: "fulltags",
    block: [
      "  megadj rb-playlist [drive] reconcile [--apply --yes] [--json]",
      "                                               XML-twin healer (F7): find",
      "                                               djmdPlaylist rows missing their",
      "                                               masterPlaylists6.xml NODE (RB7",
      "                                               stores Ids as HEX — decimal",
      "                                               matches lie); apply adds the",
      "                                               missing NODEs with backups",
      "                                               (dry first)",
    ],
  },
  {
    name: "rb-playlist",
    group: "fulltags",
    block: [
      "  megadj rb-playlist [drive] [--preset P] [--minutes N] [--opener ID]",
      "                                               [--playlist NAME] [--group NAME] [--limit N]",
      "                                               [--genre FAMILY] [--apply --yes] [--json]",
      "                                               set-builder chain → playlist in",
      "                                               the shelf master DB (no new",
      "                                               content rows — links existing",
      "                                               ones by filename; --genre narrows",
      "                                               the pool by family substring;",
      "                                               dry first,",
      "                                               same gates as rb-import)",
    ],
  },
  {
    name: "rb-grid-triage",
    group: "fulltags",
    block: [
      "  megadj rb-grid-triage [drive] [--compare D] [--limit N] [--json]",
      "                                               grid audit vs the ANLZ rekordbox wrote:",
      "                                               byte-compare vs a stick (--compare = SYNC",
      "                                               issues → re-export) then decode the PQTZ",
      "                                               grid + audit the ledger (SHIFT/PHASE/",
      "                                               TEMPO/DRIFT/CHAOS) — read-only",
    ],
  },
  {
    name: "rb-anlz-spike",
    group: "fulltags",
    block: [
      "  megadj rb-anlz-spike [drive] snapshot|compare|set-grid --tag T",
      "                                               [--file KEY --beats JSON --apply --yes] [--json]",
      "                                               GA-07 write-path spike: hash + inventory",
      "                                               sidecars before/after a manual rekordbox",
      "                                               experiment; set-grid = Q4's direct PQTZ",
      "                                               rewrite (dry-run default, backup +",
      "                                               re-verify on --apply --yes)",
    ],
  },
];
