/**
 * Metadata enrichment for rekordbox.
 *
 * Strategy (best source wins, in order):
 *  1. yt-dlp web_music client metadata (auto-generated by YouTube from the
 *     label feed — includes artist, album, release date, ISRC credits)
 *  2. musicbrainz-recorder lookup by artist/title when album is missing
 *  3. Genre inference from YouTube Music category tags
 *
 * Tags are written with ffmpeg so rekordbox gets a complete picture:
 * title, artist, album, album artist, genre, date, comment (source URL),
 * and a composer field carrying the producer credits when available.
 */

import { $ } from "bun";

export interface EnrichedMetadata {
  title: string | null;
  artist: string | null;
  albumArtist: string | null;
  album: string | null;
  genre: string | null;
  date: string | null;
  composer: string | null;
  comment: string | null;
  bpm: number | null;
}

export interface YtdlpInfo {
  title?: string;
  artist?: string;
  album?: string;
  genre?: string;
  categories?: string[];
  channel?: string;
  uploader?: string;
  release_year?: number;
  release_date?: string;
  upload_date?: string;
  description?: string;
  webpage_url?: string;
  duration?: number;
  ext?: string;
}

/** Genre → folder name safe for filesystems ("R&B / Soul" → "R&B Soul"). */
export function sanitizeGenreFolder(genre: string): string {
  return genre
    .replace(/\s*\/\s*/g, " ")
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

// Word-bounded patterns only — substring matches put "Soulji Remix" in
// R&B and "Rise Of A ChamSET" wait no, but genuinely: "Sunset" in House etc.
const GENRE_MAP: Array<[RegExp, string]> = [
  [/\b(?:hip.?hop|rap|trap|drill)\b/i, "Hip-Hop"],
  [/\b(?:r&b|soul|neo.?soul)\b/i, "R&B / Soul"],
  [/\b(?:deep house|tech house|afro house|house|house music)\b/i, "House"],
  [/\b(?:techno|trance|hardstyle|psytrance)\b/i, "Techno / Trance"],
  [
    /\b(?:edm|electro|dubstep|bass|dnb|drum.?and.?bass|drum.?n.?bass)\b/i,
    "EDM / Bass",
  ],
  [/\b(?:lofi|lo.?fi|chill|downtempo|ambient)\b/i, "Chill / Lo-Fi"],
  [/\b(?:reggae|dancehall|afrobeat|afro beats?)\b/i, "Reggae / Afro"],
  [/\b(?:rock|metal|punk|indie rock)\b/i, "Rock"],
  [/\b(?:jazz|blues|soul jazz)\b/i, "Jazz / Blues"],
  [/\b(?:country|folk|americana)\b/i, "Country / Folk"],
  [/\b(?:classical|orchestra|symphony|piano solo)\b/i, "Classical"],
  [/\bpop\b/i, "Pop"],
];

export function inferGenre(
  inputs: Array<string | null | undefined>,
): string | null {
  const blob = inputs.filter(Boolean).join(" ").toLowerCase();
  if (!blob) return null;
  // Channel "- Topic" uploads and explicit genre tags carry the most signal.
  for (const [pattern, genre] of GENRE_MAP) {
    if (pattern.test(blob)) return genre;
  }
  return null;
}

/** Extract "Producer: X" style credits from a YouTube description. */
export function extractComposer(
  description: string | null | undefined,
): string | null {
  if (!description) return null;
  const lines = description.split(/\r?\n/).map((l) => l.trim());
  const producers: string[] = [];
  for (const line of lines) {
    const m = line.match(/^(?:Producer|Produced by|Prod\.? by)[:\s]+(.+)$/i);
    if (m?.[1]) producers.push(m[1].trim());
  }
  if (producers.length === 0) return null;
  // Dedupe and cap; rekordbox composer column has room but not infinite.
  return [...new Set(producers)].slice(0, 3).join(", ");
}

/** Clean a YouTube video title into a plausible track title. */
export function cleanTitle(raw: string | null | undefined): string | null {
  if (!raw) return null;
  return raw
    .replace(/\(Official (?:Audio|Video|Music Video|Lyric Video)\)/gi, "")
    .replace(/\[Official (?:Audio|Video|Music Video|Lyric Video)\]/gi, "")
    .replace(/\(Official\)/gi, "")
    .replace(/\((?:Lyric[s]?|Audio|Video)\)/gi, "")
    .replace(/\[(?:Lyric[s]?|Audio|Video)\]/gi, "")
    .replace(/\(feat\. /gi, "(ft. ")
    .replace(/“|”/g, '"')
    .replace(/‘|’/g, "'")
    .replace(/\s{2,}/g, " ")
    .trim();
}

export function buildMetadata(info: YtdlpInfo): EnrichedMetadata {
  const title = cleanTitle(info.title) ?? info.title ?? null;
  const artist = info.artist?.trim() || null;
  const album = info.album?.trim() || null;
  const date =
    info.release_date ||
    (info.release_year ? String(info.release_year) : null) ||
    info.upload_date ||
    null;
  const composer = extractComposer(info.description);
  const genre =
    inferGenre([info.genre, info.artist, info.album, info.title]) ?? "Music";
  const albumArtist = artist && album ? artist : null;

  return {
    title,
    artist,
    albumArtist,
    album,
    genre,
    date: date?.slice(0, 4) ?? null,
    composer,
    comment: info.webpage_url ?? null,
    bpm: null, // analysis happens in rekordbox itself
  };
}

/**
 * Write enriched tags into the m4a using ffmpeg. Mutagen-style atom
 * writing via ffmpeg keeps the embedded artwork intact.
 */
export async function applyTags(
  filePath: string,
  meta: EnrichedMetadata,
): Promise<void> {
  // Explicit a+v mapping avoids the m4a ipod muxer choking on bin_data/text
  // and PNG-cover streams under a blanket `-c copy` ("Tag text incompatible
  // with output codec id"). Maps are optional ("?") because stripped files
  // may have no video stream at all. Audio is stream-copied (bit-identical);
  // a cover, when present, is re-encoded to mjpeg (the m4a attached-pic
  // codec) and flagged attached_pic.
  const args: string[] = [
    "-y",
    "-i",
    filePath,
    "-map",
    "0:a",
    "-map",
    "0:v?",
    "-c:a",
    "copy",
    "-c:v",
    "mjpeg",
    "-disposition:v:0",
    "attached_pic",
  ];
  if (meta.title) args.push("-metadata", `title=${meta.title}`);
  if (meta.artist) args.push("-metadata", `artist=${meta.artist}`);
  if (meta.albumArtist)
    args.push("-metadata", `album_artist=${meta.albumArtist}`);
  if (meta.album) args.push("-metadata", `album=${meta.album}`);
  if (meta.genre) args.push("-metadata", `genre=${meta.genre}`);
  if (meta.date) args.push("-metadata", `date=${meta.date}`);
  if (meta.composer) args.push("-metadata", `composer=${meta.composer}`);
  // Rekordbox reads the comment field; carrying the source URL makes
  // provenance traceable without polluting other fields.
  if (meta.comment) args.push("-metadata", `comment=${meta.comment}`);
  const tagged = filePath.replace(/(\.[^.]+)$/, ".tagged$1");
  args.push("-f", "ipod", tagged);

  const proc = await $`ffmpeg -hide_banner -loglevel error ${args}`.quiet();
  if (proc.exitCode !== 0) {
    throw new Error(`ffmpeg tag write failed for ${filePath}`);
  }
  // Atomic swap via rename — a crash can never leave a half-written original.
  await $`mv -f ${tagged} ${filePath}`.quiet();
}
