/**
 * Metadata enrichment for rekordbox.
 *
 * Strategy (best source wins, in order):
 *  1. yt-dlp web_music client metadata (auto-generated by YouTube from the
 *     label feed — includes artist, album, release date, ISRC credits)
 *  2. musicbrainz-recorder lookup by artist/title when album is missing
 *  3. Genre inference from YouTube Music category tags
 *
 * Tags are written with ffmpeg so rekordbox gets a complete picture:
 * title, artist, album, album artist, genre, date, comment (source URL),
 * and a composer field carrying the producer credits when available.
 */

import { $ } from "bun";
import { extname } from "node:path";

export interface EnrichedMetadata {
  title: string | null;
  artist: string | null;
  albumArtist: string | null;
  album: string | null;
  genre: string | null;
  date: string | null;
  composer: string | null;
  comment: string | null;
  bpm: number | null;
  /** Remix credit ("Flozone Flip") — written to the version/remix tag. */
  remixer?: string | null;
  /** Style/scene grouping (rekordbox reads grouping) for library filters. */
  grouping?: string | null;
  /** MusicBrainz recording MBID — provenance for future enrichment passes. */
  mbid?: string | null;
}

export interface YtdlpInfo {
  title?: string;
  artist?: string;
  album?: string;
  genre?: string;
  categories?: string[];
  channel?: string;
  uploader?: string;
  release_year?: number;
  release_date?: string;
  upload_date?: string;
  description?: string;
  webpage_url?: string;
  duration?: number;
  ext?: string;
}

/** Genre → folder name safe for filesystems ("R&B / Soul" → "R&B Soul"). */
export function sanitizeGenreFolder(genre: string): string {
  return genre
    .replace(/\s*\/\s*/g, " ")
    .replace(/[\\/:*?"<>|]/g, "")
    .replace(/\s+/g, " ")
    .trim();
}

// Word-bounded patterns only — substring matches put "Soulji Remix" in
// R&B and "Rise Of A ChamSET" wait no, but genuinely: "Sunset" in House etc.
const GENRE_MAP: Array<[RegExp, string]> = [
  [/\b(?:hip.?hop|rap|trap|drill)\b/i, "Hip-Hop"],
  [/\b(?:r&b|soul|neo.?soul)\b/i, "R&B / Soul"],
  [/\b(?:deep house|tech house|afro house|house|house music)\b/i, "House"],
  [/\b(?:techno|trance|hardstyle|psytrance)\b/i, "Techno / Trance"],
  [
    /\b(?:edm|electro|dubstep|bass|dnb|drum.?and.?bass|drum.?n.?bass)\b/i,
    "EDM / Bass",
  ],
  [/\b(?:lofi|lo.?fi|chill|downtempo|ambient)\b/i, "Chill / Lo-Fi"],
  [/\b(?:reggae|dancehall|afrobeat|afro beats?)\b/i, "Reggae / Afro"],
  [/\b(?:rock|metal|punk|indie rock)\b/i, "Rock"],
  [/\b(?:jazz|blues|soul jazz)\b/i, "Jazz / Blues"],
  [/\b(?:country|folk|americana)\b/i, "Country / Folk"],
  [/\b(?:classical|orchestra|symphony|piano solo)\b/i, "Classical"],
  [/\bpop\b/i, "Pop"],
];

export function inferGenre(
  inputs: Array<string | null | undefined>,
): string | null {
  const blob = inputs.filter(Boolean).join(" ").toLowerCase();
  if (!blob) return null;
  // Channel "- Topic" uploads and explicit genre tags carry the most signal.
  for (const [pattern, genre] of GENRE_MAP) {
    if (pattern.test(blob)) return genre;
  }
  return null;
}

/** Extract "Producer: X" style credits from a YouTube description. */
export function extractComposer(
  description: string | null | undefined,
): string | null {
  if (!description) return null;
  const lines = description.split(/\r?\n/).map((l) => l.trim());
  const producers: string[] = [];
  for (const line of lines) {
    const m = line.match(/^(?:Producer|Produced by|Prod\.? by)[:\s]+(.+)$/i);
    if (m?.[1]) producers.push(m[1].trim());
  }
  if (producers.length === 0) return null;
  // Dedupe and cap; rekordbox composer column has room but not infinite.
  return [...new Set(producers)].slice(0, 3).join(", ");
}

/** Clean a YouTube video title into a plausible track title. */
export function cleanTitle(raw: string | null | undefined): string | null {
  if (!raw) return null;
  return raw
    .replace(/\(Official (?:Audio|Video|Music Video|Lyric Video)\)/gi, "")
    .replace(/\[Official (?:Audio|Video|Music Video|Lyric Video)\]/gi, "")
    .replace(/\(Official\)/gi, "")
    .replace(/\((?:Lyric[s]?|Audio|Video)\)/gi, "")
    .replace(/\[(?:Lyric[s]?|Audio|Video)\]/gi, "")
    .replace(/\(feat\. /gi, "(ft. ")
    .replace(/“|”/g, '"')
    .replace(/‘|’/g, "'")
    .replace(/\s{2,}/g, " ")
    .trim();
}

export function buildMetadata(info: YtdlpInfo): EnrichedMetadata {
  const title = cleanTitle(info.title) ?? info.title ?? null;
  const artist = info.artist?.trim() || null;
  const album = info.album?.trim() || null;
  const date =
    info.release_date ||
    (info.release_year ? String(info.release_year) : null) ||
    info.upload_date ||
    null;
  const composer = extractComposer(info.description);
  const genre =
    inferGenre([info.genre, info.artist, info.album, info.title]) ?? "Music";
  const albumArtist = artist && album ? artist : null;

  return {
    title,
    artist,
    albumArtist,
    album,
    genre,
    date: date?.slice(0, 4) ?? null,
    composer,
    comment: info.webpage_url ?? null,
    bpm: null, // analysis happens in rekordbox itself
  };
}

/**
 * Write enriched tags into the m4a using ffmpeg. Mutagen-style atom
 * writing via ffmpeg keeps the embedded artwork intact.
 */
export async function applyTags(
  filePath: string,
  meta: EnrichedMetadata,
): Promise<void> {
  // AIFF special case: ffmpeg's aiff muxer DROPS the ID3 chunk (verified —
  // title degrades to an annotation chunk, artist/APIC vanish). AIFF tag
  // writes go through mutagen instead, which edits the ID3 chunk in place
  // and keeps any embedded artwork intact.
  const extLower = extname(filePath).toLowerCase();
  if (extLower === ".aiff" || extLower === ".aif") {
    await applyTagsAiff(filePath, meta);
    return;
  }
  // Explicit a+v mapping avoids the m4a ipod muxer choking on bin_data/text
  // and PNG-cover streams under a blanket `-c copy` ("Tag text incompatible
  // with output codec id"). Maps are optional ("?") because stripped files
  // may have no video stream at all. Audio is stream-copied (bit-identical);
  // a cover, when present, is re-encoded to mjpeg (the m4a attached-pic
  // codec) and flagged attached_pic.
  const args: string[] = [
    "-y",
    "-i",
    filePath,
    "-map",
    "0:a",
    "-map",
    "0:v?",
    "-c:a",
    "copy",
    "-c:v",
    "mjpeg",
    "-disposition:v:0",
    "attached_pic",
  ];
  if (meta.title) args.push("-metadata", `title=${meta.title}`);
  if (meta.artist) args.push("-metadata", `artist=${meta.artist}`);
  if (meta.albumArtist)
    args.push("-metadata", `album_artist=${meta.albumArtist}`);
  if (meta.album) args.push("-metadata", `album=${meta.album}`);
  if (meta.genre) args.push("-metadata", `genre=${meta.genre}`);
  if (meta.date) args.push("-metadata", `date=${meta.date}`);
  if (meta.composer) args.push("-metadata", `composer=${meta.composer}`);
  // Remix credit: ID3v2.4 TXXX:version / MP4 ©rem — rekordbox shows it as
  // "Remixer" and CDJs group on it. WAV/AIFF: ffmpeg's wav muxer accepts
  // arbitrary -metadata but players ignore it; harmless to write.
  if (meta.remixer) args.push("-metadata", `version=${meta.remixer}`);
  if (meta.grouping) args.push("-metadata", `grouping=${meta.grouping}`);
  // MusicBrainz provenance — standard Picard tag, makes re-enrichment and
  // AcoustID lookups possible without re-searching.
  if (meta.mbid) args.push("-metadata", `musicbrainz_trackid=${meta.mbid}`);
  // Rekordbox reads the comment field; carrying the source URL makes
  // provenance traceable without polluting other fields.
  if (meta.comment) args.push("-metadata", `comment=${meta.comment}`);
  const tagged = filePath.replace(/(\.[^.]+)$/, ".tagged$1");
  // Container/format selection: m4a uses the ipod muxer; mp3 needs id3v2.3
  // (widest compatibility); lossless (wav/flac/aiff) stays in its own
  // container via explicit -c:a copy + matched muxer. The old behavior
  // forced ipod for everything, which is why .tagged.m4a junk appeared
  // next to WAV downloads ("Could not find tag for codec pcm_s16le").
  const ext = extname(filePath).toLowerCase();
  const isLossless = [".wav", ".flac", ".aiff", ".aif"].includes(ext);
  if (ext === ".mp3") {
    args.push("-c:v", "copy", "-write_id3v2", "1", "-id3v2_version", "3");
    args.push(tagged);
  } else if (isLossless) {
    if (ext === ".flac") {
      // FLAC supports embedded pictures — keep base video handling.
      args.push(tagged);
    } else {
      // WAV/AIFF muxers reject video streams — drop any attached pic.
      args.push("-vn", "-f", ext.slice(1), tagged);
    }
  } else {
    args.push("-f", "ipod", tagged);
  }

  const proc = await $`ffmpeg -hide_banner -loglevel error ${args}`.quiet();
  if (proc.exitCode !== 0) {
    throw new Error(`ffmpeg tag write failed for ${filePath}`);
  }
  // Atomic swap via rename — a crash can never leave a half-written original.
  await $`mv -f ${tagged} ${filePath}`.quiet();
}

/**
 * AIFF tag write via mutagen (in-place ID3v2 chunk edit; ffmpeg would drop
 * the chunk entirely). Maps EnrichedMetadata → ID3 frames:
 *   title→TIT2 artist→TPE1 albumArtist→TPE2 album→TALB genre→TCON
 *   date→TDRC composer→TCOM grouping→TIT1 remixer→TXXX:version
 *   comment→COMM mbid→UFID/http://musicbrainz.org
 */
async function applyTagsAiff(
  filePath: string,
  meta: EnrichedMetadata,
): Promise<void> {
  const frames: string[] = [];
  const esc = (s: string) => s.replace(/\\/g, "\\\\").replace(/"/g, '\\"');
  const set = (frame: string, value: string | null | undefined) => {
    if (value)
      frames.push(
        `t = ${frame}(encoding=3, text=["${esc(value)}"]); id3.add(t)`,
      );
  };
  set("TIT2", meta.title);
  set("TPE1", meta.artist);
  set("TPE2", meta.albumArtist);
  set("TALB", meta.album);
  set("TCON", meta.genre);
  set("TDRC", meta.date);
  set("TCOM", meta.composer);
  set("TIT1", meta.grouping);
  if (meta.remixer)
    frames.push(
      `t = TXXX(encoding=3, desc="version", text=["${esc(meta.remixer)}"]); id3.add(t)`,
    );
  if (meta.comment)
    frames.push(
      `t = COMM(encoding=3, lang="eng", desc="", text=["${esc(meta.comment)}"]); id3.add(t)`,
    );
  if (meta.mbid)
    frames.push(
      `t = TXXX(encoding=3, desc="MusicBrainz Track Id", text=["${esc(meta.mbid)}"]); id3.add(t)`,
    );
  const script = `
from mutagen.aiff import AIFF
from mutagen.id3 import ID3, TIT2, TPE1, TPE2, TALB, TCON, TDRC, TCOM, TIT1, TXXX, COMM
a = AIFF(${JSON.stringify(filePath)})
if a.tags is None:
    a.add_tags()
id3 = a.tags
# wipe all text frames, keep APIC (embedded art) untouched
for k in list(id3.keys()):
    if k != "APIC":
        del id3[k]
${frames.join("\n")}
a.save()
print("ok")`;
  const proc = await $`uv run --with mutagen python -c ${script}`
    .quiet()
    .nothrow();
  if (proc.exitCode !== 0 || !proc.stdout.toString().trim().includes("ok")) {
    throw new Error(
      `mutagen AIFF tag write failed for ${filePath}: ${proc.stderr.toString().slice(0, 200)}`,
    );
  }
}
