---
name: metrics-test
"on":
  workflow_dispatch:

jobs:
  snapshot:
    uses: webuildstuffio/repo-review/.github/workflows/metrics-reusable.yml@main
    with:
      run_snapshot: true
      language: typescript
    secrets: inherit
